{% set version = "0.23.1" %}
{% set python_min = "3.13" %}

package:
  name: quart
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/q/quart/quart-{{ version }}.tar.gz
  sha256: 1ca848415910bd2eb75e9d9b452388f892a37be222602a373622e6c633d1efbf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - quart = quart.cli:main

requirements:
  host:
    - pip
    - flit-core <=4.0.0
    - python {{ python_min }}
  run:
    - aiofiles
    - blinker >=1.6
    - click >=8.0.0
    - flask >=3.0.0
    - hypercorn >=0.11.2
    - itsdangerous
    - jinja2
    - markupsafe
    - python >={{ python_min }}
    - werkzeug >=3.0.0

test:
  imports:
    - quart
  requires:
    - pip
    - m2-grep  # [win]
    - python {{ python_min }}
  commands:
    - pip check
    - quart --version
    - quart --version | grep -iE "Quart {{ version.replace(".", "\.") }}"

about:
  home: https://github.com/pallets/quart
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python ASGI web microframework with the same API as Flask
  description: |
    Quart is a Python ASGI web microframework. It is intended to provide the easiest way to use
    asyncio functionality in a web context, especially with existing Flask
    apps. This is possible as the Quart API is a superset of the Flask API.
    Quart aims to be a complete web microframework, as it supports
    HTTP/1.1, HTTP/2 and websockets. Quart is very extendable and has a
    number of known extensions and works
    with many of the Flask extensions.
  doc_url: https://quart.palletsprojects.com

extra:
  recipe-maintainers:
    - maxyme
    - dhirschfeld
    - soapy1
